name: CI
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://sikalabs/ci
        with:
          args: |
            sh -c "
            echo $KUBECONFIG_BASE64 | base64 --decode > .kubeconfig.yml
            export KUBECONFIG=.kubeconfig.yml
            helm upgrade --install hello hello-world \
              --repo https://helm.sikalabs.io \
              --namespace test-github-actions --create-namespace \
              --set host=hello.ybug.dev
            "