name: CI
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - run: sh .ci/setup-kubeconfig.sh
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
      - uses: docker://sikalabs/helm
        with:
          args: sh .ci/deploy.sh
