name: CI
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make docker-build
      - run: make docker-push
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: sh .ci/setup-kubeconfig.sh
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
      - uses: docker://sikalabs/ci
        with:
          args: sh .ci/deploy.sh
